channels:
  - conda-forge
dependencies:
  - python==3.6
  - sphinx>=1.4
  - pandoc
  - nbconvert
  - ipykernel
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - numpy
  - deprecation
  - git
  # - nbsphinx
  - pip:
    - git+https://github.com/spatialaudio/nbsphinx.git@master
