channels:
  - conda-forge
dependencies:
  - python=3.6
  - sphinx>=1.4
  - pandoc
  - nbconvert
  - ipykernel
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - numpy
  - deprecation
  - git
  - nbsphinx
 # - scipy
 # - matplotlib
 # - h5py
 # - netCDF4
 # - gdal
  - xmltodict
